# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: crop.dvgamerr.app

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      # AdSense envs (prefer Secrets, fallback to Repository/Org Variables)
      PROD: true
      VITE_ADSENSE_CLIENT: ${{ vars.VITE_ADSENSE_CLIENT }}
      VITE_ADSENSE_SLOT: ${{ vars.VITE_ADSENSE_SLOT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build 🔧
        run: bun i

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build 🔧
        run: bun run build

      - name: Upload artifact 🚀
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4